<template>
  <div class="modal">
    <h1 style="text-align: center">라인추가</h1>
  </div>
</template>

<script>
export default {
  emits: [''],
  setup() {},
};
</script>

<style scoped>
.modal {
  z-index: 102;
  width: 40vw;
  height: 50vh;
  background: white;
  position: fixed;
  -webkit-animation: scale-up-center 0.2s cubic-bezier(0.39, 0.575, 0.565, 1) both;
  animation: scale-up-center 0.2s cubic-bezier(0.39, 0.575, 0.565, 1) both;
  top: 20vh;
  left: 60vh;
  border: 1px solid #cbcbcb;
  box-sizing: border-box;
  box-shadow: 0px 4px 4px rgba(0, 0, 0, 0.44);
  border-radius: 5px;
  overflow-y: scroll;
  padding: 10px;
}

.modal::-webkit-scrollbar {
  width: 6px;
  height: 6px;
}
.modal::-webkit-scrollbar-track {
  border-radius: 10px;
  background: rgba(0, 0, 0, 0.1);
}
.modal::-webkit-scrollbar-thumb {
  border-radius: 10px;
  background: rgba(0, 0, 0, 0.2);
}
.modal::-webkit-scrollbar-thumb:hover {
  background: rgba(0, 0, 0, 0.4);
}
.modal::-webkit-scrollbar-thumb:active {
  background: rgba(0, 0, 0, 0.9);
}

.button-blue {
  display: flex;
  align-items: center;
  justify-content: center;
  width: 100%;
  height: 100px;
  margin: 0 auto;
  background: #748bde;
  border-radius: 20px;
  color: white;
  font-weight: bold;
  font-size: 36px;
  font-family: 'GmarketSansMedium';
  margin-bottom: 10px;
  cursor: pointer;
}

.selected {
  background: #cbcbcb;
  cursor: default;
}

.scale-up-center {
  -webkit-animation: scale-up-center 0.2s cubic-bezier(0.39, 0.575, 0.565, 1) both;
  animation: scale-up-center 0.2s cubic-bezier(0.39, 0.575, 0.565, 1) both;
}
/* ----------------------------------------------
 * Generated by Animista on 2022-3-29 14:47:0
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation scale-up-center
 * ----------------------------------------
 */
@-webkit-keyframes scale-up-center {
  0% {
    -webkit-transform: scale(0.5);
    transform: scale(0.5);
  }
  100% {
    -webkit-transform: scale(1);
    transform: scale(1);
  }
}
@keyframes scale-up-center {
  0% {
    -webkit-transform: scale(0.5);
    transform: scale(0.5);
  }
  100% {
    -webkit-transform: scale(1);
    transform: scale(1);
  }
}
</style>
