<template>
  <div class="modal">
    <h1 class="modal-header">구역 추가</h1>
    <div>
      <label>구역 이름</label>
      <input type="text" class="input" v-model="state.name" />
    </div>
    <div>
      <label>양식 방법</label>
      <select class="select" v-model="state.system">
        <option value="0">일반 수하식</option>
        <option value="1">연승 수하식</option>
        <option value="2">뗏목 수하식</option>
        <option value="3">기타 수하식</option>
      </select>
    </div>
    <div>
      <label>일반부표 개수</label>
      <input type="text" class="input" v-model="state.plain_buoy" />
    </div>

    <div>
      <button class="button-blue" v-on:click="addGroup">추가하기</button>
    </div>
  </div>
</template>

<script>
import { reactive } from '@vue/reactivity';
import api from '@/api/api';

export default {
  setup() {
    let state = reactive({
      name: '',
      system: 0,
      plain_buoy: '',
    });

    async function addGroup() {
      if (isNaN(parseInt(state.plain_buoy))) {
        alert('입력값을 확인해 주세요');
        return;
      }

      if (state.name === '') {
        alert('입력값을 확인해 주세요');
        return;
      }

      if (confirm('등록하시겠습니까?')) {
        let param = {
          group_name: state.name,
          group_system: state.system,
          plain_buoy: parseInt(state.plain_buoy),
        };

        let result = await api._POST('detail/group/create', param);
        console.log(result);

        if (result.code === 1) {
          alert('새로운 그룹을 생성했습니다.');
          location.href = '/detail';
        } else {
          alert('다시 시도해 주세요.');
        }
      }
    }
    return { state, addGroup };
  },
};
</script>

<style scoped>
.modal-header {
  font-family: 'GmarketSansMedium';
  text-align: center;
  margin: 10px;
}
.modal {
  z-index: 102;
  width: 30vw;
  height: 500px;
  background: white;
  position: fixed;
  -webkit-animation: scale-up-center 0.2s cubic-bezier(0.39, 0.575, 0.565, 1) both;
  animation: scale-up-center 0.2s cubic-bezier(0.39, 0.575, 0.565, 1) both;
  top: 20vh;
  left: 35vw;
  border: 1px solid #cbcbcb;
  box-sizing: border-box;
  box-shadow: 0px 4px 4px rgba(0, 0, 0, 0.44);
  border-radius: 5px;
  padding: 20px;
}

.modal::-webkit-scrollbar {
  width: 6px;
  height: 6px;
}
.modal::-webkit-scrollbar-track {
  border-radius: 10px;
  background: rgba(0, 0, 0, 0.1);
}
.modal::-webkit-scrollbar-thumb {
  border-radius: 10px;
  background: rgba(0, 0, 0, 0.2);
}
.modal::-webkit-scrollbar-thumb:hover {
  background: rgba(0, 0, 0, 0.4);
}
.modal::-webkit-scrollbar-thumb:active {
  background: rgba(0, 0, 0, 0.9);
}

.button-blue {
  display: flex;
  align-items: center;
  justify-content: center;
  width: 200px;
  height: 50px;
  margin: 50px auto 0px auto;
  background: blue;
  border-radius: 10px;
  border: none;
  color: white;
  font-size: 16px;
  font-family: 'GmarketSansMedium';
  margin-bottom: 10px;
  cursor: pointer;
}

.selected {
  background: #cbcbcb;
  cursor: default;
}

.scale-up-center {
  -webkit-animation: scale-up-center 0.2s cubic-bezier(0.39, 0.575, 0.565, 1) both;
  animation: scale-up-center 0.2s cubic-bezier(0.39, 0.575, 0.565, 1) both;
}
/* ----------------------------------------------
 * Generated by Animista on 2022-3-29 14:47:0
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation scale-up-center
 * ----------------------------------------
 */
@-webkit-keyframes scale-up-center {
  0% {
    -webkit-transform: scale(0.5);
    transform: scale(0.5);
  }
  100% {
    -webkit-transform: scale(1);
    transform: scale(1);
  }
}
@keyframes scale-up-center {
  0% {
    -webkit-transform: scale(0.5);
    transform: scale(0.5);
  }
  100% {
    -webkit-transform: scale(1);
    transform: scale(1);
  }
}

label {
  font-size: 18px;
  color: #606060;
}

.input-area {
  margin-bottom: 30px;
}

.input {
  margin-top: 5px;
  margin-bottom: 20px;
  border-top: none;
  border-left: none;
  border-right: none;
  border-bottom: 1px solid #606060;
  background: none;
  display: block;
  height: 30px;
  color: #606060;
  width: 100%;
  font-size: 16px;
}

.select {
  margin-top: 10px;
  margin-bottom: 20px;
  border-top: none;
  border-left: none;
  border-right: none;
  border-bottom: 1px solid #606060;
  background: none;
  display: block;
  height: 30px;
  color: #606060;
  width: 100%;
  font-size: 16px;
}

.select::placeholder {
  color: #9a9a9a;
}

.select:focus {
  outline: none;
  border-bottom: 2px solid #c8c8c8;
}
.input::placeholder {
  color: #9a9a9a;
}

.input:focus {
  outline: none;
  border-bottom: 2px solid #c8c8c8;
}
</style>
