<template>
  <div class="register-wrapper slide-in-blurred-left">
    <div class="input-group">
      <RegisterInputWithButton :data="buttonInput.email" @check_duple="check_duple" @send_key="send_key" />
      <RegisterInputWithButton :data="buttonInput.key" v-if="buttonInput.email.is_submitted" @auth_email="auth_email" />
      <RegisterInput v-for="data in plainInput" :data="data" :key="data" />
    </div>

    <button class="button" v-on:click="submit">시작하기</button>
  </div>
</template>

<script>
import { reactive } from '@vue/reactivity';
import axios from 'axios';
import RegisterInput from './child/RegisterInput.vue';
import RegisterInputWithButton from './child/RegisterInputWithButton.vue';
import { useStore } from 'vuex';
import { useRouter } from 'vue-router';
export default {
  components: { RegisterInput, RegisterInputWithButton },
  setup() {
    let store = useStore();
    let router = useRouter();
    let url = store.getters.url;
    let buttonInput = reactive({
      email: {
        title: '이메일',
        value: '',
        is_checked: false,
        is_submitted: false,
      },
      key: {
        title: '인증번호',
        value: '',
        is_checked: true,
      },
    });

    let plainInput = reactive({
      pw1: {
        title: '비밀번호',
        value: '',
      },
      pw2: {
        title: '비밀번호 확인',
        value: '',
      },
      name: {
        title: '이름',
        value: '',
      },
    });

    let state = reactive({
      email: '',
      done: false,
    });

    function check_duple() {
      let regex = /^[0-9a-zA-Z]([-_.]?[0-9a-zA-Z])*@[0-9a-zA-Z]([-_.]?[0-9a-zA-Z])*.[a-zA-Z]{2,3}$/i;

      if (!regex.test(buttonInput.email.value)) {
        alert('이메일 주소를 확인해 주세요');
        return;
      }

      axios.post(url + '/user/check', { email: buttonInput.email.value }).then((response) => {
        if (response.data.message === 0) {
          alert('사용 가능한 이메일 주소 입니다. 메일 인증을 해주세요.');

          //중간에 이메일 바꾸는거 방지
          state.email = buttonInput.email.value;

          buttonInput.email.is_checked = true;
        } else {
          alert('이미 사용중인 이메일 주소 입니다.');
        }
      });
    }

    function send_key() {
      axios.post(url + '/user/email/key', { email: state.email }).then((response) => {
        if (response.data.code === 1) {
          alert('입력한 이메일로 인증코드를 전송했습니다. 메일함을 확인해 주세요.');
          buttonInput.email.is_submitted = true;
        } else {
          alert('인증코드 전송에 실패했습니다. 다시 시도해 주세요.');
        }
      });
    }

    function auth_email() {
      axios.post(url + '/user/email/auth', { email: state.email, code: buttonInput.key.value }).then((response) => {
        if (response.data.code === 1) {
          alert('이메일 인증을 완료 했습니다. 회원가입을 진행해 주세요.');
          state.done = true;
        } else {
          alert('인증에 실패 했습니다. 다시 시도해 주세요.');
        }
      });
    }

    function submit() {
      if (plainInput.pw1.value !== plainInput.pw2.value) {
        alert('비밀번호가 일치하지 않습니다. 확인해주세요.');
        return;
      }

      let param = {
        email: state.email,
        password: plainInput.pw1.value,
        name: plainInput.name.value,
      };

      if (confirm('회원가입을 진행하시겠습니까?')) {
        axios.post(url + '/user/register', param).then((response) => {
          if (response.data.code === 1) {
            alert('회원가입을 완료했습니다. 로그인 해주세요');
            router.push('/login');
          } else {
            alert('회원가입을 실패 했습니다. 다시 시도해 주세요.');
          }
        });
      }
    }

    return { buttonInput, plainInput, check_duple, send_key, auth_email, submit };
  },
};
</script>

<style scoped>
.register-wrapper {
  width: 85%;
  padding-top: 60px;
  height: 100%;
  display: flex;
  flex-direction: column;
}

.input-group {
  flex-wrap: wrap;
}
.button {
  width: 100%;
  height: 45px;
  border: none;
  background: #f09553;
  border-radius: 20px;
  margin: auto 0px 50px 0px;
  color: white;
  font-weight: bold;
  font-size: 16px;
  cursor: pointer;
}

hr {
  width: 85%;
}

.slide-in-blurred-left {
  -webkit-animation: slide-in-blurred-left 0.6s cubic-bezier(0.23, 1, 0.32, 1) both;
  animation: slide-in-blurred-left 0.6s cubic-bezier(0.23, 1, 0.32, 1) both;
}

/* ----------------------------------------------
 * Generated by Animista on 2022-5-3 15:54:6
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation slide-in-blurred-left
 * ----------------------------------------
 */
@-webkit-keyframes slide-in-blurred-left {
  0% {
    -webkit-transform: translateX(-1000px) scaleX(2.5) scaleY(0.2);
    transform: translateX(-1000px) scaleX(2.5) scaleY(0.2);
    -webkit-transform-origin: 100% 50%;
    transform-origin: 100% 50%;
  }
  100% {
    -webkit-transform: translateX(0) scaleY(1) scaleX(1);
    transform: translateX(0) scaleY(1) scaleX(1);
    -webkit-transform-origin: 50% 50%;
    transform-origin: 50% 50%;
  }
}
@keyframes slide-in-blurred-left {
  0% {
    -webkit-transform: translateX(-1000px) scaleX(2.5) scaleY(0.2);
    transform: translateX(-1000px) scaleX(2.5) scaleY(0.2);
    -webkit-transform-origin: 100% 50%;
    transform-origin: 100% 50%;
  }
  100% {
    -webkit-transform: translateX(0) scaleY(1) scaleX(1);
    transform: translateX(0) scaleY(1) scaleX(1);
    -webkit-transform-origin: 50% 50%;
    transform-origin: 50% 50%;
  }
}
</style>
