<template>
  <div class="main-group-container">
    <div class="top_menu"><img class="menu-svg" src="../../../../../assets/list.svg" v-on:click="onclick" /></div>

    <hr class="head_line" />

    <div class="title"><button class="area-button">A 구역 평균</button></div>

    <div class="info-area">
      <InfoCard :data="state.content[0]" />
      <div class="line"><div class="circle"></div></div>
      <div>평균 높이입니다</div>

      <div>주의 하셔야 해요</div>
      <div class="line"><div class="circle"></div></div>
      <InfoCard :data="state.content[1]" />

      <InfoCard :data="state.content[2]" />
      <div class="line"><div class="circle"></div></div>
      <div></div>

      <div>현재위치</div>
      <div class="line"><div class="circle"></div></div>
      <MainLocation />
    </div>
  </div>
</template>

<script>
import { reactive } from '@vue/reactivity';
import InfoCard from './InfoCard.vue';
import MainLocation from './MainLocation.vue';

export default {
  components: { InfoCard, MainLocation },
  setup() {
    let state = reactive({
      content: [
        {
          icon: 'buoy',
          description: '해수면으로부터 평균 높이',
          data: '40cm',
        },
        {
          icon: 'weight',
          description: '구역 부표 평균 무게',
          data: '30kg',
        },
        {
          icon: 'etc',
          description: '그외 다른 정보',
          data: '40cm',
        },
      ],
    });

    function onclick() {
      console.log('asd');
    }

    return { state, onclick };
  },
};
</script>

<style scoped>
.main-group-container {
  display: flex;
  flex-direction: column;
}

.top_menu {
  display: flex;
  justify-content: flex-end;
}

.menu-svg {
  width: 48px;
  cursor: pointer;
}

.title {
  display: flex;
  justify-content: center;
}

.area-button {
  background: #748bde;
  border: none;
  border-radius: 20px;
  width: 220px;
  height: 65px;
  color: white;
  font-weight: bold;
  font-size: 24px;
  font-family: 'GmarketSansMedium';
}

.head_line {
  margin: 5px 0px 24px 0px;
}

.info-area {
  display: grid;
  column-gap: 30px;
  grid-template-columns: 1fr 0.01fr 1fr;
}

.line {
  margin: 0 auto;
  width: 1px;
  background: #748bde;
  border: 4px solid #748bde;
}

.circle {
  border-radius: 100px;
  border: 18px solid #748bde;
  margin-top: 50px;
  margin-left: -17.5px;
}

/* anim */

.slide-in-fwd-center {
  -webkit-animation: slide-in-fwd-center 0.4s cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
  animation: slide-in-fwd-center 0.4s cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
}

/* ----------------------------------------------
 * Generated by Animista on 2022-3-28 16:22:26
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation slide-in-fwd-center
 * ----------------------------------------
 */
@-webkit-keyframes slide-in-fwd-center {
  0% {
    -webkit-transform: translateZ(-1400px);
    transform: translateZ(-1400px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateZ(0);
    transform: translateZ(0);
    opacity: 1;
  }
}
@keyframes slide-in-fwd-center {
  0% {
    -webkit-transform: translateZ(-1400px);
    transform: translateZ(-1400px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateZ(0);
    transform: translateZ(0);
    opacity: 1;
  }
}
</style>
