<template>
  <div class="specify-container">
    <img class="bouy_img" :src="props.data.warn ? require('@/assets/buoy_img_warn.svg') : require('@/assets/buoy_img.svg')" />
    <span class="number">{{ props.data.model.slice(5) }}</span>
  </div>
</template>

<script>
export default {
  components: {},
  props: {
    data: Object,
  },
  setup(props) {
    return { props };
  },
};
</script>

<style scope>
.specify-container {
  display: flex;
  align-items: center;
  justify-content: center;
  position: relative;
  cursor: pointer;
}

.specify-container:hover {
  -webkit-animation: pulsate-bck 0.5s ease-in-out both;
  animation: pulsate-bck 0.5s ease-in-out both;
}

.bouy_img {
  width: 80%;
}

.bouy_img:hover {
}

.number {
  position: absolute;
  top: 25%;
  color: #929292;
  font-weight: bold;
  font-size: 1.5rem;
}

.modal-wrapper {
  display: none;
  z-index: 101;
  position: fixed;
  top: 0px;
  left: 0px;
  width: 100%;
  height: 100vh;
  background: rgb(0, 0, 0, 0.5);
}
/* ----------------------------------------------
 * Generated by Animista on 2022-3-30 15:12:27
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation pulsate-bck
 * ----------------------------------------
 */
@-webkit-keyframes pulsate-bck {
  0% {
    -webkit-transform: scale(1);
    transform: scale(1);
  }
  50% {
    -webkit-transform: scale(0.9);
    transform: scale(0.9);
  }
  100% {
    -webkit-transform: scale(1);
    transform: scale(1);
  }
}
@keyframes pulsate-bck {
  0% {
    -webkit-transform: scale(1);
    transform: scale(1);
  }
  50% {
    -webkit-transform: scale(0.9);
    transform: scale(0.9);
  }
  100% {
    -webkit-transform: scale(1);
    transform: scale(1);
  }
}
</style>
