<template>
  <div>
    <div class="linear" ref="linear">
      <div class="line" v-on:click="onClick">
        <div class="circle"></div>
        <div class="circle"></div>
        <div class="circle"></div>
        <div class="circle"></div>
        <div class="circle"></div>
        <div class="circle"></div>
        <div class="circle"></div>
        <div class="circle"></div>
      </div>
      <img
        :src="require('@/assets/bottom_arrow.svg')"
        style="cursor: pointer"
        v-if="!state.isClicked"
        v-on:click="onClick"
      />
      <img
        :src="require('@/assets/top_arrow.svg')"
        style="cursor: pointer"
        v-if="state.isClicked"
        v-on:click="onClick"
      />

      <div class="detail-info" v-if="state.isClicked">
        <hr />
        <canvas id="myChart" width="400" height="400" ref="myChart"></canvas>
      </div>
    </div>
  </div>
</template>

<script>
import { reactive, ref } from '@vue/reactivity';
import { onMounted } from '@vue/runtime-core';
export default {
  components: {},
  setup() {
    let linear = ref(null);
    let state = reactive({
      isClicked: false,
    });

    function onClick() {
      state.isClicked = !state.isClicked;

      if (state.isClicked) {
        linear.value.appendC;
        linear.value.style.height = '600px';
      } else {
        linear.value.style.height = '60px';
      }
    }

    onMounted(() => {});

    return { state, onClick, linear };
  },
};
</script>

<style scoped>
.linear {
  width: 100%;
  height: 60px;
  background: #ffffff;
  border-radius: 20px;
  filter: drop-shadow(0px 4px 4px rgba(0, 0, 0, 0.25));
  padding: 0px 5px 0px 5px;
  display: grid;
  align-items: center;
  align-content: stretch;

  grid-template-columns: 2fr 0.1fr;
  grid-template-rows: 60px 1fr;
}

.line {
  width: 90%;
  height: 2px;
  border: 1px solid #748bde;
  background: #748bde;
  border-radius: 2px;
  display: flex;
  justify-content: space-between;
  cursor: pointer;
}

.circle {
  background: #ff7777;
  border-radius: 100px;
  border: 15px solid #ff7777;
  margin: -13px -2px 0px -2px;
}

.detail-info {
  grid-column: 1 / 3;
  padding: 0px 10px 0px 10px;
}

.scale_up {
  -webkit-animation: scale-up-ver-top 0.4s cubic-bezier(0.39, 0.575, 0.565, 1)
    both;
  animation: scale-up-ver-top 0.4s cubic-bezier(0.39, 0.575, 0.565, 1) both;
}

/* ----------------------------------------------
 * Generated by Animista on 2022-3-29 21:10:1
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation scale-up-ver-top
 * ----------------------------------------
 */
@-webkit-keyframes scale-up-ver-top {
  0% {
    -webkit-transform: scaleY(0.4);
    transform: scaleY(0.4);
    -webkit-transform-origin: 100% 0%;
    transform-origin: 100% 0%;
  }
  100% {
    -webkit-transform: scaleY(1);
    transform: scaleY(1);
    -webkit-transform-origin: 100% 0%;
    transform-origin: 100% 0%;
  }
}
@keyframes scale-up-ver-top {
  0% {
    -webkit-transform: scaleY(0.4);
    transform: scaleY(0.4);
    -webkit-transform-origin: 100% 0%;
    transform-origin: 100% 0%;
  }
  100% {
    -webkit-transform: scaleY(1);
    transform: scaleY(1);
    -webkit-transform-origin: 100% 0%;
    transform-origin: 100% 0%;
  }
}
</style>
