<template>
  <div class="linear" ref="linear">
    <div class="line">
      <div v-for="(line, index) in state.lineArr" :key="line">
        <div v-if="state.clickedLine[index]" class="text" :class="{ left_side_border: index == 0 }">{{ line._line_info.line }}번 라인</div>
        <div v-else :class="{ blue_box: index % 2 == 0, sky_box: index % 2 == 1 }" v-on:click="onClick(index)"></div>
      </div>

      <div class="plus-box" v-on:click="onclickPlusMenu"><img :src="require('@/assets/plus.svg')" class="plus" /></div>
    </div>

    <Detailinfo @onclickBouyMenu="onclickBouyMenu" :line="state.line" :key="state.line" v-if="state.isLoading" />

    <div class="modal-wrapper fade-in" ref="modal_wrapper" v-on:click="closeModal"></div>
  </div>

  <BouyModal v-if="state.isBouyModal" :data="state.modalData" />
  <PlusModal v-if="state.isPlusModal" />

  <div class="modal-wrapper fade-in" ref="modal_wrapper" v-on:click="closeModal"></div>
</template>

<script>
import { reactive, ref } from '@vue/reactivity';
import { onMounted } from '@vue/runtime-core';
import Detailinfo from './LinearComponents/Detail_info.vue';
import BouyModal from './LinearComponents/modal/BouyModal.vue';
import PlusModal from './LinearComponents/modal/PlusModal.vue';

import { useRoute } from 'vue-router';

export default {
  components: { Detailinfo, BouyModal, PlusModal },
  props: {
    line: Array,
  },
  setup(props) {
    let linear = ref(null);
    const modal_wrapper = ref(null);
    const route = useRoute();

    let state = reactive({
      clickedLine: [],
      trueLine: 0,
      isBouyModal: false,
      isPlusModal: false,
      modalData: {},
      lineArr: [],
      line: {},
      isLoading: false,
    });

    onMounted(() => {
      init();

      if (route.params.data) {
        let data = JSON.parse(route.params.data);
        onClick(data.line - 1);
      }
    });

    function init() {
      state.lineArr = props.line;

      props.line.forEach((v, idx) => {
        if (idx === 0) {
          state.line = v;
          state.clickedLine.push(true);
        } else {
          state.clickedLine.push(false);
        }
      });

      state.isLoading = true;
    }

    function onClick(index) {
      console.log(index);
      state.clickedLine[state.trueLine] = false;
      state.line = props.line[index];
      state.trueLine = index;
      state.clickedLine[state.trueLine] = true;
    }

    function onclickBouyMenu(data) {
      state.modalData = data;
      state.isBouyModal = true;
      modal_wrapper.value.style.display = 'block';
    }

    function onclickPlusMenu() {
      state.isPlusModal = true;
      modal_wrapper.value.style.display = 'block';
    }

    function closeModal() {
      state.isBouyModal = false;
      state.isPlusModal = false;

      modal_wrapper.value.style.display = 'none';
    }

    return {
      state,
      onClick,
      linear,
      closeModal,
      onclickBouyMenu,
      modal_wrapper,
      onclickPlusMenu,
      props,
    };
  },
};
</script>

<style scoped>
.linear {
  width: 100%;
  height: auto;

  display: grid;
  align-items: center;
  align-content: stretch;
  grid-template-columns: 2fr 0.1fr;
  grid-template-rows: 60px 1fr;
  grid-column: 1 / 3;
  gap: 0px;
}

.line {
  width: 90%;
  /* height: 2px; */
  /* border: 1px solid #a1c2c9; */
  /* background: #a1c2c9; */
  border-radius: 2px;
  display: flex;
  justify-content: flex-start;
  cursor: pointer;
  margin: 0px;
}

.text {
  font-weight: bold;
  font-size: 28px;
  background: #ffffff;
  border: 1px solid #c4c9d3;
  border-bottom: none;
  border-radius: 0px 0px 0px 0px;
  width: 180px;
  height: 58px;
  padding: 0px;
  margin: 0px;
  display: flex;
  align-items: center;
  justify-content: center;
  cursor: pointer;
  user-select: none;
}

.left_side_border {
  border-radius: 20px 0px 0px 0px;
}

.circle {
  background: #c0e4e9;
  border-radius: 100px;
  border: 15px solid #c0e4e9;
  margin: -13px -2px 0px -2px;
}

.modal-wrapper {
  display: none;
  z-index: 101;
  position: fixed;
  top: 0px;
  left: 0px;
  width: 100%;
  height: 100vh;
  background: rgb(0, 0, 0, 0.5);
}

.blue_box {
  background: #748bde;
  width: 59px;
  height: 59px;
}

.sky_box {
  background: #85abf4;
  width: 59px;
  height: 59px;
}

.plus-box {
  width: 59px;
  height: 59px;
  display: flex;
  align-items: center;
  justify-content: center;
  background: #edeff5;
}

.plus {
  width: 24px;
}

.pink {
  background: #ffd1da !important;
  border-color: #ffd1da !important;
}

.scale_up {
  -webkit-animation: scale-up-ver-top 0.4s cubic-bezier(0.39, 0.575, 0.565, 1) both;
  animation: scale-up-ver-top 0.4s cubic-bezier(0.39, 0.575, 0.565, 1) both;
}

/* ----------------------------------------------
 * Generated by Animista on 2022-3-29 21:10:1
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation scale-up-ver-top
 * ----------------------------------------
 */
@-webkit-keyframes scale-up-ver-top {
  0% {
    -webkit-transform: scaleY(0.4);
    transform: scaleY(0.4);
    -webkit-transform-origin: 100% 0%;
    transform-origin: 100% 0%;
  }
  100% {
    -webkit-transform: scaleY(1);
    transform: scaleY(1);
    -webkit-transform-origin: 100% 0%;
    transform-origin: 100% 0%;
  }
}
@keyframes scale-up-ver-top {
  0% {
    -webkit-transform: scaleY(0.4);
    transform: scaleY(0.4);
    -webkit-transform-origin: 100% 0%;
    transform-origin: 100% 0%;
  }
  100% {
    -webkit-transform: scaleY(1);
    transform: scaleY(1);
    -webkit-transform-origin: 100% 0%;
    transform-origin: 100% 0%;
  }
}
</style>
